<?php


/**
 * Implements hook_block_info().
 */
function pmh_testimonials_block_info() {
  $blocks['pmh_testimonials'] = array(
    'info' => t('PMH Testimonials Block'),
    'cache' => DRUPAL_NO_CACHE
  );

  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function pmh_testimonials_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'pmh_testimonials':

      // Path the module.
      $base_path = drupal_get_path('module', 'pmh_testimonials');

      // Add custom js.
      drupal_add_js($base_path . '/js/pmh_testimonials.js');

      $block['subject'] = '';
      $block['content'] = array(
        '#theme' => 'pmh_testimonials',
        '#testimonials' => pmh_testimonials_nodes(),
      );

      break;
  }
  return $block;
}

/**
 * Implements hook_custom_theme().
 */
function pmh_testimonials_theme() {
  return array(
    'pmh_testimonials' => array(
      'template' => 'templates/pmh_testimonials',
      'variables' => array(
        'testimonials' => NULL,
      ),
    ),
  );
}


// Custom function to return all the hero banner nodes.
function pmh_testimonials_nodes(){

  // Empty array to return later.
  $out = array();
  $items = array();

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node') // Query nodes.
    ->entityCondition('bundle', 'testimonials') // Hero banner content type.
    ->addMetaData('account', user_load(1)); // Run the query as user 1.
  $result = $query->execute(); // Execute that funky function.

  if (isset($result['node'])) {
    // Returned node IDs.
    $nids = array_keys($result['node']);
    // Load the nodes with provided nids.
    $items = entity_load('node', $nids);
  }
  // If there are nodes.
  if (!empty($items)) {
    foreach ($items as $k => $v) {
      $out[$k]['body'] = $v->body['und'][0]['value'];
      $out[$k]['field_full_name'] = $v->field_full_name['und'][0]['value'];
      $out[$k]['field_read_more_link'] = $v->field_read_more_link['und'][0]['value'];
    }
  }
  return $out;
}